import { execFileSync } from 'node:child_process';

/**
 * Real images generated by the ffmpeg of the container, for the custom
 * thumbnail tests. `color` makes two images of the same size differ.
 */
export function generateImage(
  format: 'jpeg' | 'png' | 'webp',
  size = '800x600',
  color = 'blue',
): Buffer {
  const codec = { jpeg: 'mjpeg', png: 'png', webp: 'libwebp' }[format];
  const muxer = format === 'webp' ? 'webp' : 'image2';
  return execFileSync('ffmpeg', [
    '-v',
    'error',
    '-f',
    'lavfi',
    '-i',
    `color=c=${color}:size=${size}`,
    '-frames:v',
    '1',
    '-c:v',
    codec,
    '-f',
    muxer,
    'pipe:1',
  ]);
}
