import * as childProcess from 'node:child_process';
import { execFileSync } from 'node:child_process';
import type { ConfigType } from '@nestjs/config';
import { InvalidImageException } from '../../common/exceptions/domain.exception';
import type videoConfig from '../../config/video.config';
import { readJpegSize } from '../../test/media-fixtures';
import { ImageNormalizerService } from './image-normalizer.service';

jest.mock('node:child_process', () => {
  const actual =
    jest.requireActual<typeof import('node:child_process')>(
      'node:child_process',
    );
  return { ...actual, spawn: jest.fn(actual.spawn) };
});

const config = (
  overrides: Partial<ConfigType<typeof videoConfig>> = {},
): ConfigType<typeof videoConfig> => ({
  partSizeBytes: 67108864,
  workerConcurrency: 1,
  processingTimeoutMs: 1_800_000,
  thumbnailMaxPixels: 16_777_216,
  thumbnailDecodeTimeoutMs: 5_000,
  ...overrides,
});

// Real images generated by the ffmpeg of the container.
const generate = (size: string, format: 'png' | 'mjpeg' | 'webp'): Buffer =>
  execFileSync('ffmpeg', [
    '-v',
    'error',
    '-f',
    'lavfi',
    '-i',
    `testsrc=size=${size}`,
    '-frames:v',
    '1',
    '-c:v',
    format === 'png' ? 'png' : format === 'webp' ? 'libwebp' : 'mjpeg',
    '-f',
    format === 'png' ? 'image2' : format === 'webp' ? 'webp' : 'image2',
    'pipe:1',
  ]);

/** Inserts an APP1 Exif segment carrying a GPS marker right after SOI. */
const withExif = (jpegImage: Buffer): Buffer => {
  const payload = Buffer.concat([
    Buffer.from('Exif\0\0', 'binary'),
    Buffer.from('GPSLatitude=-23.5505;GPSLongitude=-46.6333', 'ascii'),
  ]);
  const segment = Buffer.alloc(4);
  segment.writeUInt16BE(0xffe1, 0);
  segment.writeUInt16BE(payload.length + 2, 2);
  return Buffer.concat([
    jpegImage.subarray(0, 2),
    segment,
    payload,
    jpegImage.subarray(2),
  ]);
};

const bigPngHeader = (): Buffer => {
  const buffer = Buffer.alloc(33);
  Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]).copy(buffer, 0);
  buffer.writeUInt32BE(13, 8);
  buffer.write('IHDR', 12, 'ascii');
  buffer.writeUInt32BE(16000, 16);
  buffer.writeUInt32BE(16000, 20);
  return buffer;
};

const ffmpegProcesses = (): number => {
  try {
    return Number(execFileSync('pgrep', ['-c', '-x', 'ffmpeg']).toString());
  } catch {
    return 0; // pgrep exits 1 when nothing matches
  }
};

/** A WebP header with the VP8X animation flag (the frames do not matter). */
const animatedWebpHeader = (): Buffer => {
  const buffer = Buffer.alloc(30);
  buffer.write('RIFF', 0, 'ascii');
  buffer.writeUInt32LE(22, 4);
  buffer.write('WEBP', 8, 'ascii');
  buffer.write('VP8X', 12, 'ascii');
  buffer.writeUInt32LE(10, 16);
  buffer[20] = 0x02;
  buffer.writeUIntLE(99, 24, 3);
  buffer.writeUIntLE(99, 27, 3);
  return buffer;
};

describe('ImageNormalizerService (integration, real ffmpeg)', () => {
  const spawn = childProcess.spawn as unknown as jest.Mock;

  beforeEach(() => spawn.mockClear());

  it('re-encodes a 1920x1080 JPEG with GPS EXIF as a 640x360 JPEG without EXIF', async () => {
    const input = withExif(generate('1920x1080', 'mjpeg'));
    expect(input.includes(Buffer.from('Exif'))).toBe(true);

    const output = await new ImageNormalizerService(config()).normalize(input);

    expect(readJpegSize(output)).toEqual({ width: 640, height: 360 });
    expect(output.includes(Buffer.from('Exif'))).toBe(false);
    expect(output.includes(Buffer.from('GPSLatitude'))).toBe(false);
  });

  it.each([
    ['PNG', () => generate('800x600', 'png')],
    ['static WebP', () => generate('800x600', 'webp')],
  ])('re-encodes a %s as a JPEG 640 px wide', async (_kind, make) => {
    const output = await new ImageNormalizerService(config()).normalize(make());

    expect(output.subarray(0, 3)).toEqual(Buffer.from([0xff, 0xd8, 0xff]));
    expect(readJpegSize(output).width).toBe(640);
  });

  it('refuses text named like an image', async () => {
    await expect(
      new ImageNormalizerService(config()).normalize(
        Buffer.from('this is not a png'),
      ),
    ).rejects.toBeInstanceOf(InvalidImageException);
  });

  it('refuses a 16000x16000 PNG before starting any ffmpeg process', async () => {
    await expect(
      new ImageNormalizerService(config()).normalize(bigPngHeader()),
    ).rejects.toBeInstanceOf(InvalidImageException);
    expect(spawn).not.toHaveBeenCalled();
  });

  it('refuses an animated WebP without decoding it', async () => {
    await expect(
      new ImageNormalizerService(config()).normalize(animatedWebpHeader()),
    ).rejects.toBeInstanceOf(InvalidImageException);
    expect(spawn).not.toHaveBeenCalled();
  });

  it('refuses a corrupted PNG after ffmpeg fails to decode it', async () => {
    const corrupted = Buffer.from(generate('800x600', 'png'));
    corrupted.fill(0, 40); // keeps signature and IHDR, destroys the data

    await expect(
      new ImageNormalizerService(config()).normalize(corrupted),
    ).rejects.toBeInstanceOf(InvalidImageException);
    expect(spawn).toHaveBeenCalledTimes(1);
  });

  it('kills ffmpeg and refuses the image when the decoding times out', async () => {
    const service = new ImageNormalizerService(
      config({ thumbnailDecodeTimeoutMs: 1 }),
    );

    await expect(
      service.normalize(generate('1920x1080', 'png')),
    ).rejects.toBeInstanceOf(InvalidImageException);
    await new Promise((resolve) => setTimeout(resolve, 200));
    expect(ffmpegProcesses()).toBe(0);
  });
});
